const DESTINATIONS = [
  // Spiritual (India)
  {
    id: 1,
    name: 'Varanasi, Uttar Pradesh',
    state: 'Uttar Pradesh',
    country: 'India',
    region: 'North India',
    bestTime: 'Oct – Mar',
    priceLevel: '$$',
    category: 'Spiritual',
    badge: 'Sacred Yatra',
    lat: 25.3176,
    lng: 82.9739,
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80',
    description: 'The eternal spiritual capital of India along the sacred river Ganges, home to Kashi Vishwanath temple.'
  },
  {
    id: 2,
    name: 'Ayodhya, Uttar Pradesh',
    state: 'Uttar Pradesh',
    country: 'India',
    region: 'North India',
    bestTime: 'Oct – Mar',
    priceLevel: '$$',
    category: 'Spiritual',
    badge: 'Shri Ram Mandir',
    lat: 26.7922,
    lng: 82.1998,
    image: 'https://images.unsplash.com/photo-1609946782782-96c21e6c3e98?w=800&auto=format&fit=crop&q=80',
    description: 'Ancient holy city on the banks of Sarayu, birthplace of Lord Rama.'
  },
  {
    id: 3,
    name: 'Rishikesh, Uttarakhand',
    state: 'Uttarakhand',
    country: 'India',
    region: 'North India',
    bestTime: 'Sep – Apr',
    priceLevel: '$$',
    category: 'Spiritual',
    badge: 'Yoga Capital',
    lat: 30.0869,
    lng: 78.2676,
    image: 'https://images.unsplash.com/photo-1596895111956-bf1cf0599ce5?w=800&auto=format&fit=crop&q=80',
    description: 'Sacred town on the foothills of Himalayas, famous for yoga retreats, ashrams, and Ganga Aarti.'
  },
  {
    id: 4,
    name: 'Kedarnath, Uttarakhand',
    state: 'Uttarakhand',
    country: 'India',
    region: 'North India',
    bestTime: 'May – Oct',
    priceLevel: '$$$',
    category: 'Spiritual',
    badge: 'Chardham Yatra',
    lat: 30.7352,
    lng: 79.0669,
    image: 'https://images.unsplash.com/photo-1626715693005-efb553e110b6?w=800&auto=format&fit=crop&q=80',
    description: 'One of the holiest Jyotirlingas of Lord Shiva, nestled in the snow-clad Garhwal Himalayas.'
  },
  {
    id: 5,
    name: 'Badrinath, Uttarakhand',
    state: 'Uttarakhand',
    country: 'India',
    region: 'North India',
    bestTime: 'May – Oct',
    priceLevel: '$$$',
    category: 'Spiritual',
    badge: 'Chardham Yatra',
    lat: 30.7433,
    lng: 79.4938,
    image: 'https://images.unsplash.com/photo-1617653202545-930ccf05646d?w=800&auto=format&fit=crop&q=80',
    description: 'Sacred shrine of Lord Vishnu located along the Alaknanda River in Uttarakhand.'
  },
  {
    id: 6,
    name: 'Puri, Odisha',
    state: 'Odisha',
    country: 'India',
    region: 'East India',
    bestTime: 'Oct – Feb',
    priceLevel: '$$',
    category: 'Spiritual',
    badge: 'Jagannath Dham',
    lat: 19.8135,
    lng: 85.8312,
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80',
    description: 'Coastal spiritual hub famous for the historic Shree Jagannath Temple and Rath Yatra festival.'
  },
  {
    id: 7,
    name: 'Dwarka, Gujarat',
    state: 'Gujarat',
    country: 'India',
    region: 'West India',
    bestTime: 'Oct – Mar',
    priceLevel: '$$',
    category: 'Spiritual',
    badge: 'Lord Krishna Kingdom',
    lat: 22.2442,
    lng: 68.9685,
    image: 'https://images.unsplash.com/photo-1601999109332-542b18dbec57?w=800&auto=format&fit=crop&q=80',
    description: 'Ancient kingdom of Lord Krishna, located on the tip of the Saurashtra peninsula.'
  },
  {
    id: 8,
    name: 'Rameshwaram, Tamil Nadu',
    state: 'Tamil Nadu',
    country: 'India',
    region: 'South India',
    bestTime: 'Oct – Mar',
    priceLevel: '$$$',
    category: 'Spiritual',
    badge: 'Sacred Island',
    lat: 9.2876,
    lng: 79.3129,
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80',
    description: 'Island yatra site where Lord Rama built the bridge to Lanka, featuring Ramanathaswamy Temple.'
  },
  {
    id: 9,
    name: 'Madurai, Tamil Nadu',
    state: 'Tamil Nadu',
    country: 'India',
    region: 'South India',
    bestTime: 'Oct – Mar',
    priceLevel: '$$',
    category: 'Spiritual',
    badge: 'Meenakshi Temple',
    lat: 9.9252,
    lng: 78.1198,
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800&auto=format&fit=crop&q=80',
    description: 'Historic city featuring the grand architecture of Meenakshi Amman Temple and Gopurams.'
  },
  {
    id: 10,
    name: 'Tirupati, Andhra Pradesh',
    state: 'Andhra Pradesh',
    country: 'India',
    region: 'South India',
    bestTime: 'Sep – Mar',
    priceLevel: '$$$',
    category: 'Spiritual',
    badge: 'Venkateswara Balaji',
    lat: 13.6284,
    lng: 79.4192,
    image: 'https://images.unsplash.com/photo-1620802879494-3b2b7f330d24?w=800&auto=format&fit=crop&q=80',
    description: 'Hill shrine of Lord Venkateswara at Tirumala, one of the most visited pilgrimage spots.'
  },
  {
    id: 11,
    name: 'Shirdi, Maharashtra',
    state: 'Maharashtra',
    country: 'India',
    region: 'West India',
    bestTime: 'Oct – Mar',
    priceLevel: '$$',
    category: 'Spiritual',
    badge: 'Sai Baba Temple',
    lat: 19.7662,
    lng: 74.4762,
    image: 'https://images.unsplash.com/photo-1631856955365-b77864f1d63e?w=800&auto=format&fit=crop&q=80',
    description: 'Sacred home of Sai Baba, promoting universal harmony and spiritual peace.'
  },
  {
    id: 12,
    name: 'Amritsar, Punjab',
    state: 'Punjab',
    country: 'India',
    region: 'North India',
    bestTime: 'Oct – Mar',
    priceLevel: '$$',
    category: 'Spiritual',
    badge: 'Golden Temple',
    lat: 31.6340,
    lng: 74.8723,
    image: 'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?w=800&auto=format&fit=crop&q=80',
    description: 'Home of the magnificent Harmandir Sahib (Golden Temple), the spiritual center of Sikhism.'
  },
  {
    id: 13,
    name: 'Mathura & Vrindavan, UP',
    state: 'Uttar Pradesh',
    country: 'India',
    region: 'North India',
    bestTime: 'Oct – Mar',
    priceLevel: '$',
    category: 'Spiritual',
    badge: 'Brij Bhoomi',
    lat: 27.4924,
    lng: 77.6737,
    image: 'https://images.unsplash.com/photo-1590076214227-f4955b2049e0?w=800&auto=format&fit=crop&q=80',
    description: 'Sacred cities dedicated to Lord Krishna’s childhood pastimes, flute songs, and Holi celebrations.'
  },

  // Heritage & Historical (India)
  {
    id: 14,
    name: 'Jaipur, Rajasthan',
    state: 'Rajasthan',
    country: 'India',
    region: 'North India',
    bestTime: 'Nov – Feb',
    priceLevel: '$$$',
    category: 'Heritage',
    badge: 'Pink City',
    lat: 26.9124,
    lng: 75.7873,
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
    description: 'Royal capital of Rajasthan, famous for Hawa Mahal, Amer Fort, and historic palaces.'
  },
  {
    id: 15,
    name: 'Udaipur, Rajasthan',
    state: 'Rajasthan',
    country: 'India',
    region: 'North India',
    bestTime: 'Nov – Feb',
    priceLevel: '$$$$',
    category: 'Heritage',
    badge: 'City of Lakes',
    lat: 24.5854,
    lng: 73.7125,
    image: 'https://images.unsplash.com/photo-1593693411515-c202e974fe08?w=800&auto=format&fit=crop&q=80',
    description: 'Romantic city of white marble palaces overlooking tranquil Lake Pichola.'
  },
  {
    id: 16,
    name: 'Jodhpur, Rajasthan',
    state: 'Rajasthan',
    country: 'India',
    region: 'North India',
    bestTime: 'Nov – Feb',
    priceLevel: '$$$',
    category: 'Heritage',
    badge: 'Blue City',
    lat: 26.2389,
    lng: 73.0243,
    image: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=800&auto=format&fit=crop&q=80',
    description: 'Historic city featuring blue-painted houses below the massive Mehrangarh Fort.'
  },
  {
    id: 17,
    name: 'Agra, Uttar Pradesh',
    state: 'Uttar Pradesh',
    country: 'India',
    region: 'North India',
    bestTime: 'Nov – Mar',
    priceLevel: '$$$',
    category: 'Heritage',
    badge: 'Taj Mahal',
    lat: 27.1767,
    lng: 78.0081,
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80',
    description: 'Home of the Taj Mahal, Agra Fort, and rich architectural remnants of the Mughal Empire.'
  },
  {
    id: 18,
    name: 'Hampi, Karnataka',
    state: 'Karnataka',
    country: 'India',
    region: 'South India',
    bestTime: 'Oct – Mar',
    priceLevel: '$$',
    category: 'Heritage',
    badge: 'Vijayanagara Ruins',
    lat: 15.3350,
    lng: 76.4600,
    image: 'https://images.unsplash.com/photo-1600100397608-f010e42fa4bf?w=800&auto=format&fit=crop&q=80',
    description: 'UNESCO World Heritage site containing the majestic stone ruins of the Vijayanagara Empire.'
  },
  {
    id: 19,
    name: 'Khajuraho, Madhya Pradesh',
    state: 'Madhya Pradesh',
    country: 'India',
    region: 'Central India',
    bestTime: 'Oct – Mar',
    priceLevel: '$$$',
    category: 'Heritage',
    badge: 'Chandel Temples',
    lat: 24.8318,
    lng: 79.9199,
    image: 'https://images.unsplash.com/photo-1616781708896-189f36f6d895?w=800&auto=format&fit=crop&q=80',
    description: 'Famous group of temples featuring intricate medieval carvings and symbolic stone structures.'
  },
  {
    id: 20,
    name: 'Ajanta & Ellora Caves, Maharashtra',
    state: 'Maharashtra',
    country: 'India',
    region: 'West India',
    bestTime: 'Oct – Mar',
    priceLevel: '$$',
    category: 'Heritage',
    badge: 'Rock-Cut Temples',
    lat: 20.0268,
    lng: 75.1771,
    image: 'https://images.unsplash.com/photo-1608958416755-e9cc5036127d?w=800&auto=format&fit=crop&q=80',
    description: 'Ancient rock-cut caves housing the monolithic Kailash Temple and historical paintings.'
  },
  {
    id: 21,
    name: 'Mysore, Karnataka',
    state: 'Karnataka',
    country: 'India',
    region: 'South India',
    bestTime: 'Oct – Mar',
    priceLevel: '$$',
    category: 'Heritage',
    badge: 'Mysore Palace',
    lat: 12.2958,
    lng: 76.6394,
    image: 'https://images.unsplash.com/photo-1582103444431-7b3b9b47e2cc?w=800&auto=format&fit=crop&q=80',
    description: 'Vibrant city showcasing royal heritage, Mysore Palace illumination, and sandalwood crafts.'
  },

  // Nature & Hills (India)
  {
    id: 22,
    name: 'Munnar, Kerala',
    state: 'Kerala',
    country: 'India',
    region: 'South India',
    bestTime: 'Sep – May',
    priceLevel: '$$$',
    category: 'Nature',
    badge: 'Tea Plantations',
    lat: 10.0889,
    lng: 77.0595,
    image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80',
    description: 'Scenic hill station engulfed in emerald tea estates, mist-covered valleys, and rare flora.'
  },
  {
    id: 23,
    name: 'Ooty, Tamil Nadu',
    state: 'Tamil Nadu',
    country: 'India',
    region: 'South India',
    bestTime: 'Oct – Jun',
    priceLevel: '$$$',
    category: 'Nature',
    badge: 'Blue Hills',
    lat: 11.4102,
    lng: 76.6950,
    image: 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=800&auto=format&fit=crop&q=80',
    description: 'Popular Nilgiri hill station with colonial architecture, botanical gardens, and toy train rides.'
  },
  {
    id: 24,
    name: 'Manali, Himachal Pradesh',
    state: 'Himachal Pradesh',
    country: 'India',
    region: 'North India',
    bestTime: 'Oct – Jun',
    priceLevel: '$$$',
    category: 'Nature',
    badge: 'Himalayan Gateway',
    lat: 32.2396,
    lng: 77.1887,
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800&auto=format&fit=crop&q=80',
    description: 'Snowy adventure hub offering paragliding, skiing in Solang Valley, and Solang snow peaks.'
  },
  {
    id: 25,
    name: 'Darjeeling, West Bengal',
    state: 'West Bengal',
    country: 'India',
    region: 'East India',
    bestTime: 'Oct – May',
    priceLevel: '$$$',
    category: 'Nature',
    badge: 'Kanchenjunga View',
    lat: 27.0410,
    lng: 88.2627,
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80',
    description: 'Hill station famed for organic tea gardens and sunrise views over Mount Kanchenjunga.'
  },
  {
    id: 26,
    name: 'Gangtok, Sikkim',
    state: 'Sikkim',
    country: 'India',
    region: 'North East India',
    bestTime: 'Oct – May',
    priceLevel: '$$$',
    category: 'Nature',
    badge: 'Buddhist Monasteries',
    lat: 27.3314,
    lng: 88.6138,
    image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=800&auto=format&fit=crop&q=80',
    description: 'Clean mountain city close to Tsomgo Lake, monasteries, and scenic viewpoints.'
  },
  {
    id: 27,
    name: 'Gulmarg, Kashmir',
    state: 'Jammu & Kashmir',
    country: 'India',
    region: 'North India',
    bestTime: 'Nov – Feb',
    priceLevel: '$$$$',
    category: 'Nature',
    badge: 'Meadow of Flowers',
    lat: 34.0484,
    lng: 74.3805,
    image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=800&auto=format&fit=crop&q=80',
    description: 'Winter wonderland featuring snow valleys, ski slopes, and the high Gulmarg Gondola.'
  },
  {
    id: 28,
    name: 'Leh-Ladakh, India',
    state: 'Ladakh',
    country: 'India',
    region: 'North India',
    bestTime: 'Jun – Sep',
    priceLevel: '$$$$',
    category: 'Nature',
    badge: 'Cold Desert',
    lat: 34.1526,
    lng: 77.5771,
    image: 'https://images.unsplash.com/photo-1581791538302-03537b9c97bf?w=800&auto=format&fit=crop&q=80',
    description: 'High-altitude cold desert with turquoise Pangong Lake and winding mountain passes.'
  },

  // Beach & Island (India)
  {
    id: 29,
    name: 'Swaraj Dweep (Havelock), Andaman',
    state: 'Andaman & Nicobar',
    country: 'India',
    region: 'Islands',
    bestTime: 'Oct – May',
    priceLevel: '$$$$',
    category: 'Beach & Island',
    badge: 'Radhanagar Beach',
    lat: 11.9699,
    lng: 92.9841,
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80',
    description: 'Tropical paradise featuring crystal-clear azure waters and fine coral diving reef spots.'
  },
  {
    id: 30,
    name: 'Goa, India',
    state: 'Goa',
    country: 'India',
    region: 'West India',
    bestTime: 'Nov – Feb',
    priceLevel: '$$$',
    category: 'Beach & Island',
    badge: 'Sun, Sand & Sea',
    lat: 15.2993,
    lng: 74.1240,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    description: 'Popular coastal state famed for beaches, Portuguese churches, and vibrant local cuisine.'
  },
  {
    id: 31,
    name: 'Gokarna, Karnataka',
    state: 'Karnataka',
    country: 'India',
    region: 'South India',
    bestTime: 'Oct – Mar',
    priceLevel: '$$',
    category: 'Beach & Island',
    badge: 'Mahabaleshwar temple',
    lat: 14.5479,
    lng: 74.3188,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    description: 'Quiet temple town near the coast, famous for Om Beach, half-moon beaches, and Lord Shiva temple.'
  },
  {
    id: 32,
    name: 'Pondicherry, India',
    state: 'Pondicherry',
    country: 'India',
    region: 'South India',
    bestTime: 'Oct – Mar',
    priceLevel: '$$$',
    category: 'Beach & Island',
    badge: 'French Quarter',
    lat: 11.9416,
    lng: 79.8083,
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80',
    description: 'Charming seaside destination featuring French colonial lanes, cafes, and Auroville Ashram.'
  },

  // International
  {
    id: 33,
    name: 'Kyoto, Japan',
    state: 'Kansai',
    country: 'Japan',
    region: 'International',
    bestTime: 'Mar–May, Oct-Nov',
    priceLevel: '$$$$',
    category: 'Heritage',
    badge: 'Imperial Gardens',
    lat: 35.0116,
    lng: 135.7681,
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&auto=format&fit=crop&q=80',
    description: 'Classical wooden temples, gardens, Shinto shrines, and geisha districts.'
  },
  {
    id: 34,
    name: 'Bali, Indonesia',
    state: 'Bali',
    country: 'Indonesia',
    region: 'International',
    bestTime: 'Apr – Oct',
    priceLevel: '$$$',
    category: 'Beach & Island',
    badge: 'Island of Gods',
    lat: -8.4095,
    lng: 115.1889,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=80',
    description: 'Tropical beaches, volcanos, terraced rice paddies, and ancient Hindu shrines.'
  },
  {
    id: 35,
    name: 'Paris, France',
    state: 'Île-de-France',
    country: 'France',
    region: 'International',
    bestTime: 'Apr – Oct',
    priceLevel: '$$$$',
    category: 'Heritage',
    badge: 'Eiffel Tower',
    lat: 48.8566,
    lng: 2.3522,
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&auto=format&fit=crop&q=80',
    description: 'City of light, fashion, cafe culture, and historical landmarks like Louvre and Eiffel Tower.'
  },
  {
    id: 36,
    name: 'Rome, Italy',
    state: 'Lazio',
    country: 'Italy',
    region: 'International',
    bestTime: 'Apr – Oct',
    priceLevel: '$$$$',
    category: 'Heritage',
    badge: 'Colosseum Ruins',
    lat: 41.9028,
    lng: 12.4964,
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&auto=format&fit=crop&q=80',
    description: 'Eternal city hosting the Colosseum, Roman Forum, Trevi Fountain, and Vatican City.'
  },
  {
    id: 37,
    name: 'Cairo, Egypt',
    state: 'Cairo',
    country: 'Egypt',
    region: 'International',
    bestTime: 'Oct – Apr',
    priceLevel: '$$$',
    category: 'Heritage',
    badge: 'Giza Pyramids',
    lat: 30.0444,
    lng: 31.2357,
    image: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&auto=format&fit=crop&q=80',
    description: 'Metropolis featuring the iconic Giza Pyramid Complex and ancient Nilotic civilization artifacts.'
  },
  {
    id: 38,
    name: 'Dubai, UAE',
    state: 'Dubai',
    country: 'UAE',
    region: 'International',
    bestTime: 'Nov – Mar',
    priceLevel: '$$$$',
    category: 'Heritage',
    badge: 'Burj Khalifa',
    lat: 25.2048,
    lng: 55.2708,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&auto=format&fit=crop&q=80',
    description: 'Modern luxury shopping hub featuring Burj Khalifa and desert safari dunes.'
  },
  {
    id: 39,
    name: 'Bangkok, Thailand',
    state: 'Bangkok',
    country: 'Thailand',
    region: 'International',
    bestTime: 'Nov – Feb',
    priceLevel: '$$',
    category: 'Heritage',
    badge: 'Ornate Temples',
    lat: 13.7563,
    lng: 100.5018,
    image: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&auto=format&fit=crop&q=80',
    description: 'Vibrant street life, floating markets, and ornate Buddhist shrines like Wat Arun.'
  },
  {
    id: 40,
    name: 'Singapore',
    state: 'Singapore',
    country: 'Singapore',
    region: 'International',
    bestTime: 'All Year',
    priceLevel: '$$$$',
    category: 'Nature',
    badge: 'Garden City',
    lat: 1.3521,
    lng: 103.8198,
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&auto=format&fit=crop&q=80',
    description: 'Global financial hub featuring Gardens by the Bay, Marina Bay Sands, and green spaces.'
  },
  {
    id: 41,
    name: 'London, UK',
    state: 'England',
    country: 'United Kingdom',
    region: 'International',
    bestTime: 'May – Sep',
    priceLevel: '$$$$',
    category: 'Heritage',
    badge: 'Big Ben',
    lat: 51.5074,
    lng: -0.1278,
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ca1ad?w=800&auto=format&fit=crop&q=80',
    description: 'Capital city holding the historic Tower of London, Big Ben, and majestic palaces.'
  },
  {
    id: 42,
    name: 'New York, USA',
    state: 'New York',
    country: 'USA',
    region: 'International',
    bestTime: 'Apr – Oct',
    priceLevel: '$$$$',
    category: 'Heritage',
    badge: 'Empire State',
    lat: 40.7128,
    lng: -74.0060,
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&auto=format&fit=crop&q=80',
    description: 'Skyscraper capital featuring Times Square, Central Park, and the Statue of Liberty.'
  },
  {
    id: 43,
    name: 'Sydney, Australia',
    state: 'New South Wales',
    country: 'Australia',
    region: 'International',
    bestTime: 'Sep – Apr',
    priceLevel: '$$$$',
    category: 'Beach & Island',
    badge: 'Opera House',
    lat: -33.8688,
    lng: 151.2093,
    image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&auto=format&fit=crop&q=80',
    description: 'Harbor city famous for the Sydney Opera House, Harbour Bridge, and Bondi Beach.'
  }
];

const ACTIVITIES = [
  // Varanasi
  {
    id: 201,
    name: 'Dashashwamedh Ghat Ganga Aarti',
    city: 'Varanasi',
    category: 'Spiritual',
    cost: 0,
    duration: '90',
    description: 'Sunset prayer ceremony featuring oil lamps, Vedic chanting, and holy fire rituals.',
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=400&auto=format&fit=crop&q=80'
  },
  // Ayodhya
  {
    id: 202,
    name: 'Shri Ram Janmabhoomi Darshan',
    city: 'Ayodhya',
    category: 'Spiritual',
    cost: 0,
    duration: '120',
    description: 'Darshan at the newly built holy temple complex dedicated to Lord Rama.',
    image: 'https://images.unsplash.com/photo-1609946782782-96c21e6c3e98?w=400&auto=format&fit=crop&q=80'
  },
  // Jaipur
  {
    id: 203,
    name: 'Amber Fort Elephant Safari & Tour',
    city: 'Jaipur',
    category: 'Heritage',
    cost: 400,
    duration: '180',
    description: 'Explore royal courtyards, mirror halls, and sunset views from historical bastions.',
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=400&auto=format&fit=crop&q=80'
  },
  // Rishikesh
  {
    id: 204,
    name: 'White Water River Rafting',
    city: 'Rishikesh',
    category: 'Adventure',
    cost: 800,
    duration: '120',
    description: 'Thrilling white-water rafting in the holy rapids of the Ganga River.',
    image: 'https://images.unsplash.com/photo-1596895111956-bf1cf0599ce5?w=400&auto=format&fit=crop&q=80'
  },
  // Kedarnath
  {
    id: 205,
    name: 'Kedarnath Temple Trek',
    city: 'Kedarnath',
    category: 'Spiritual',
    cost: 500,
    duration: '360',
    description: 'Breathtaking 16km trek through valley pathways to the high Himalayan temple of Shiva.',
    image: 'https://images.unsplash.com/photo-1626715693005-efb553e110b6?w=400&auto=format&fit=crop&q=80'
  },
  // Puri
  {
    id: 206,
    name: 'Jagannath Temple Darshan',
    city: 'Puri',
    category: 'Spiritual',
    cost: 0,
    duration: '90',
    description: 'Seek blessings at the ancient, towering coastal shrine of Lord Jagannath.',
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=400&auto=format&fit=crop&q=80'
  },
  // Dwarka
  {
    id: 207,
    name: 'Dwarkadhish Temple Prayer',
    city: 'Dwarka',
    category: 'Spiritual',
    cost: 0,
    duration: '100',
    description: 'Explore the 5-story historic monument dedicated to Lord Krishna.',
    image: 'https://images.unsplash.com/photo-1601999109332-542b18dbec57?w=400&auto=format&fit=crop&q=80'
  },
  // Kyoto
  {
    id: 208,
    name: 'Kiyomizu-dera Temple Tour',
    city: 'Kyoto',
    category: 'Heritage',
    cost: 400,
    duration: '120',
    description: 'Visit the historic wooden temple stage overlooking maple valleys.',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=400&auto=format&fit=crop&q=80'
  },
  // Bali
  {
    id: 209,
    name: 'Uluwatu Sunset Kecak Dance',
    city: 'Bali',
    category: 'Culture',
    cost: 150,
    duration: '90',
    description: 'Traditional fire dance performance on a cliffside temple overlooking the ocean.',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400&auto=format&fit=crop&q=80'
  }
];

module.exports = { DESTINATIONS, ACTIVITIES };
